version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    command: celery -A celery_app worker --loglevel=info

  celery_beat:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    command: celery -A celery_app beat --loglevel=info